name = "khulark"
compatibility_date = "2024-12-24"
main = "worker/index.ts"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

# Development server settings
[dev]
port = 8787
