name = "khulark"
compatibility_date = "2025-12-24"
main = "worker/index.ts"

[vars]
CLOUDFLARE_ACCOUNT_ID = "f400e5cfc5e8cd621a3c3f9264a92bc4"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[[routes]]
pattern = "khulark.sirsean.me"
custom_domain = true

