name = "khulark"
compatibility_date = "2025-12-24"
main = "worker/index.ts"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

routes = [
  { pattern = "khulark.sirsean.me", custom_domain = true }
]


